version: '3.2'

services:
    meagendaai-api:
        image: ${DOCKER_REGISTRY-}meagendaai
        container_name: application-me-agenda-ai
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 49160:80
        environment:
            ASPNETCORE_ENVIRONMENT: Development        
        volumes:
            - "/etc/hosts:/etc/hosts:ro"
        networks:
            - meagendaai-network
        links:
            - postgresdb
            - redis
        depends_on:
            - postgresdb
            - redis
        restart: always
    postgresdb:
        image: postgres
        container_name: postgres-meagendaai-db
        ports:
            - 5432:5432
        networks:
            - meagendaai-network            
        environment:
            POSTGRES_USER: admin            
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: db-meAgendaAi
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-meagendaai-db-ui    
        volumes:
            - ./database/servers.json:/pgadmin4/servers.json
        ports:
            - 8081:8081
        networks:
            - meagendaai-network
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: 123
            PGADMIN_LISTEN_PORT: 8081
        restart: always
        depends_on:
         - postgresdb    

    redis:  
        image: redis
        container_name: redis-meagendaai        
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        environment:
            REDIS_HOST: localhost
            REDIS_PORT: 6379
        networks:
            - meagendaai-network
        volumes:
          - ./storage/redis/data:/data
        restart: always   

    redis-commander:
        container_name: redis-commander-meagendaai
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        networks:
            - meagendaai-network
        environment:
            REDIS_HOSTS: local:redis:6379
            PORT: 8091
        ports:
            - 8091:8091
        depends_on:
            - redis
networks:     
    meagendaai-network:
        driver: bridge
    