// <auto-generated />
using System;
using MeAgendaAi.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeAgendaAi.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211127181031_Map_User_PhysicalPerson_Company")]
    partial class Map_User_PhysicalPerson_Company
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DT_CREATED_AT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DT_LAST_UPDATED_AT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASS_PASSWORD");

                    b.HasKey("Id");

                    b.ToTable("TB_USERS", (string)null);
                });

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.Company", b =>
                {
                    b.HasBaseType("MeAgendaAi.Domains.Entities.User");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("DSC_DESCRIPTION");

                    b.Property<short>("LimitCancelHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("TIME_LIMITCANCELHOURS");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("IN_COMPANY_CNPJ");

                    b.ToTable("TB_COMPANY", (string)null);
                });

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.PhysicalPerson", b =>
                {
                    b.HasBaseType("MeAgendaAi.Domains.Entities.User");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CPF");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RG");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IN_PHYSICAL_PERSON_CPF");

                    b.ToTable("TB_PHYSICAL_PERSON", (string)null);
                });

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.User", b =>
                {
                    b.OwnsOne("MeAgendaAi.Domains.ValueObjects.EmailObject", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EMAIL");

                            b1.HasKey("UserId");

                            b1.HasIndex("Email")
                                .IsUnique()
                                .HasDatabaseName("IN_USERS_EMAIL");

                            b1.ToTable("TB_USERS");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.Company", b =>
                {
                    b.HasOne("MeAgendaAi.Domains.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("MeAgendaAi.Domains.Entities.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MeAgendaAi.Domains.ValueObjects.NameObject", "Name", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("NM_NAME");

                            b1.HasKey("CompanyId");

                            b1.ToTable("TB_COMPANY");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MeAgendaAi.Domains.Entities.PhysicalPerson", b =>
                {
                    b.HasOne("MeAgendaAi.Domains.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("MeAgendaAi.Domains.Entities.PhysicalPerson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MeAgendaAi.Domains.ValueObjects.NameObject", "Name", b1 =>
                        {
                            b1.Property<Guid>("PhysicalPersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("NM_NAME");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("NM_SURNAME");

                            b1.HasKey("PhysicalPersonId");

                            b1.ToTable("TB_PHYSICAL_PERSON");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalPersonId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
