name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: meagendaai # set this to the name of your Azure Web App

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # login to a private container registry.
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build container image to registry
        run: docker build . -t ${{ secrets.REGISTRY_SERVER_URL }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

      - name: Push container image to registry
        run: docker push ${{ secrets.REGISTRY_SERVER_URL }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # login to a private container registry.
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_SERVER_URL }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
